name: ptu_hostel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.0-167.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  material_design_icons_flutter: ^7.0.7296
  cloud_firestore: ^4.15.5
  firebase_messaging: ^14.7.17
  firebase_database: ^10.4.7
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
#    - assets/download.png
    - asset/download.png
